# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
